[package]
name = "pixelleve"
version = "0.1.0"
description = "Imagens prontas para a web"
edition = "2021"
rust-version = "1.90"

[lib]
name = "pixelleve_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.7.1", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
tauri = { version = "2.12.2", features = [] }
tauri-plugin-dialog = "2.8.1"
